// === 鳥類資料庫（50 種）===
// 預留欄位給後台/Cornell API 補充：photoUrl、audioUrl、illustrationUrl
import { Rarity } from './theme';

export interface Hotspot {
  name: string;
  nameEn?: string;
  lat: number;
  lng: number;
  region: 'hk' | 'world';
  subregion?: string;
  frequency: 'high' | 'medium' | 'low';
  season?: string;
}

export interface BirdSpecies {
  // 基本
  id: number;
  name: string;              // 中文
  nameEn?: string;           // English
  nameYue?: string;          // 粵語俗名
  scientificName: string;
  family: string;
  familyEn?: string;
  order: string;

  // 特徵
  size: string;
  habitat: string[];
  diet: string;
  features: string;
  funFact: string;
  funFactEn?: string;
  description: string;

  // 分布
  region: string;
  season: string;
  hotspots: Hotspot[];
  globalRange: string[];

  // 系統
  baseColor: string;
  emoji: string;
  call: string;
  tags: string[];

  // AI 辨識
  aiRecognizable: boolean;
  aiConfidence?: number;
  merlinCode?: string;
  ebirdCode?: string;

  // 媒體（預留給後台/Cornell API）
  photoUrl?: string | null;           // Cornell Macaulay Library photo
  illustrationUrl?: string | null;    // 手繪 Pokemon 風格卡圖
  audioUrl?: string | null;           // 叫聲 MP3
  mediaSource?: 'cornell' | 'inaturalist' | 'custom' | null;

  // 管理
  notionId: string;
  lastUpdated: number;
  pack: number;
  source?: 'internal' | 'remote';
}

// 簡寫輔助
const h = (name: string, lat: number, lng: number, sub: string, freq: 'high' | 'medium' | 'low', season?: string): Hotspot =>
  ({ name, lat, lng, region: 'hk', subregion: sub, frequency: freq, season });

// HK 熱點池（供多鳥共用）
const HOTSPOTS = {
  maipo: h('米埔自然保護區', 22.4869, 114.0314, '新界', 'high'),
  wetland: h('香港濕地公園', 22.4666, 114.0072, '新界', 'high'),
  luklampo: h('大埔滘自然護理區', 22.4242, 114.1759, '新界', 'high'),
  taimoshan: h('大帽山', 22.4106, 114.1244, '新界', 'medium'),
  kadoorie: h('嘉道理農場', 22.4334, 114.1189, '新界', 'high'),
  shingmun: h('城門水塘', 22.3902, 114.1378, '新界', 'high'),
  namsangwai: h('南生圍', 22.4586, 114.0422, '新界', 'high'),
  longvalley: h('塱原濕地', 22.5017, 114.1103, '新界', 'high'),
  taipo_park: h('大埔海濱公園', 22.4501, 114.1734, '新界', 'medium'),
  taipo_kau: h('大埔滘', 22.4242, 114.1759, '新界', 'medium'),
  sharp: h('尖鼻咀', 22.4839, 113.9944, '新界', 'medium'),
  shatin: h('沙田中央公園', 22.3817, 114.1910, '新界', 'high'),
  yuen_long: h('元朗公園', 22.4445, 114.0226, '新界', 'medium'),
  pakfu: h('白腹公園', 22.4369, 113.9517, '新界', 'low'),

  victoria_park: h('維多利亞公園', 22.2820, 114.1894, '香港島', 'high'),
  hkpark: h('香港公園', 22.2777, 114.1619, '香港島', 'high'),
  botanical: h('香港動植物公園', 22.2793, 114.1574, '香港島', 'high'),
  peak: h('太平山山頂', 22.2757, 114.1500, '香港島', 'medium'),
  longfu: h('龍虎山', 22.2792, 114.1364, '香港島', 'medium'),
  central_pier: h('中環海濱', 22.2847, 114.1577, '香港島', 'high'),
  harbour: h('維多利亞港', 22.2930, 114.1694, '香港島', 'high'),
  aberdeen: h('鴨脷洲', 22.2410, 114.1547, '香港島', 'high'),

  kowloon_park: h('九龍公園', 22.3005, 114.1710, '九龍', 'high'),
  lai_chi_kok: h('荔枝角公園', 22.3385, 114.1527, '九龍', 'medium'),
  tsimclock: h('尖沙咀鐘樓', 22.2940, 114.1694, '九龍', 'medium'),
  kln_tsai: h('九龍仔公園', 22.3328, 114.1771, '九龍', 'medium'),

  lantau: h('大嶼山東涌灣', 22.2844, 113.9414, '離島', 'medium'),
  fung_wong: h('鳳凰山', 22.2550, 113.9127, '離島', 'low'),
  cheung_chau: h('長洲', 22.2105, 114.0285, '離島', 'medium'),
  lamma: h('南丫島', 22.2056, 114.1187, '離島', 'medium'),
};

export const INTERNAL_SPECIES: BirdSpecies[] = [
  {
    id: 1, name: '麻雀', nameEn: 'Eurasian Tree Sparrow', nameYue: '麻雀仔', scientificName: 'Passer montanus',
    family: '麻雀科', familyEn: 'Passeridae', order: '雀形目',
    size: '14 cm', habitat: ['都市', '鄉村'], diet: '種子、小蟲',
    features: '褐色頭頂、黑色喉斑、頰部黑點',
    funFact: '麻雀會用沙子「洗沙澡」清掉身上的蟲蟲！',
    funFactEn: 'Sparrows take "dust baths" to clean parasites off their feathers!',
    description: '最常見的都市鳥類，群居性強，活潑好動。',
    region: '全港', season: '四季',
    hotspots: [HOTSPOTS.victoria_park, HOTSPOTS.kowloon_park, HOTSPOTS.shatin, HOTSPOTS.hkpark, HOTSPOTS.lai_chi_kok, HOTSPOTS.yuen_long],
    globalRange: ['亞洲', '歐洲'],
    baseColor: '#C8966A', emoji: '🐦', call: '啾啾啾',
    tags: ['留鳥', '都市鳥'],
    aiRecognizable: true, aiConfidence: 0.95, merlinCode: 'eutspa', ebirdCode: 'eutspa',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-001', lastUpdated: Date.now(), pack: 1, source: 'internal',
  },
  {
    id: 2, name: '白頭鵯', nameEn: 'Light-vented Bulbul', nameYue: '白頭翁', scientificName: 'Pycnonotus sinensis',
    family: '鵯科', familyEn: 'Pycnonotidae', order: '雀形目',
    size: '19 cm', habitat: ['都市', '森林'], diet: '水果、小蟲',
    features: '頭頂白斑、喉白腹灰',
    funFact: '白頭鵯叫聲很宏亮，就像森林裡的歌手！',
    funFactEn: 'Light-vented Bulbuls are loud singers, nicknamed "forest musicians"!',
    description: '平地最常見的中型鳴禽，叫聲響亮悅耳。',
    region: '全港', season: '四季',
    hotspots: [HOTSPOTS.hkpark, HOTSPOTS.taipo_park, HOTSPOTS.namsangwai, HOTSPOTS.kadoorie, HOTSPOTS.botanical, HOTSPOTS.victoria_park],
    globalRange: ['東亞', '東南亞'],
    baseColor: '#5B6572', emoji: '🐤', call: '巧克力——',
    tags: ['留鳥', '鳴禽'],
    aiRecognizable: true, aiConfidence: 0.92, merlinCode: 'livbul', ebirdCode: 'livbul',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-002', lastUpdated: Date.now(), pack: 1, source: 'internal',
  },
  {
    id: 3, name: '暗綠繡眼鳥', nameEn: 'Japanese White-eye', nameYue: '相思仔', scientificName: 'Zosterops japonicus',
    family: '繡眼科', familyEn: 'Zosteropidae', order: '雀形目',
    size: '11 cm', habitat: ['森林', '都市'], diet: '花蜜、小果',
    features: '眼周白圈、體羽橄欖綠',
    funFact: '繡眼鳥的眼睛旁有白圈，就像戴了眼鏡！',
    funFactEn: 'White-eyes have white rings around their eyes — like tiny glasses!',
    description: '體型嬌小，喜歡吃花蜜，叫聲清亮。',
    region: '全港', season: '四季',
    hotspots: [HOTSPOTS.peak, HOTSPOTS.shingmun, HOTSPOTS.botanical, HOTSPOTS.kln_tsai, HOTSPOTS.taipo_kau],
    globalRange: ['東亞', '東南亞'],
    baseColor: '#9BC66A', emoji: '🦜', call: '滴——溜——',
    tags: ['留鳥', '小型鳥'],
    aiRecognizable: true, aiConfidence: 0.88, merlinCode: 'jawheye', ebirdCode: 'jawheye',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-003', lastUpdated: Date.now(), pack: 1, source: 'internal',
  },
  {
    id: 4, name: '紅耳鵯', nameEn: 'Red-whiskered Bulbul', nameYue: '高髻冠', scientificName: 'Pycnonotus jocosus',
    family: '鵯科', familyEn: 'Pycnonotidae', order: '雀形目',
    size: '20 cm', habitat: ['森林', '都市'], diet: '水果',
    features: '頭頂黑冠、臉頰紅色、尖嘴',
    funFact: '紅耳鵯頭上有黑色龐克頭，兩頰有紅色小點點！',
    description: '外型討喜的都市鳥，叫聲悅耳，常成群出現。',
    region: '全港', season: '四季',
    hotspots: [HOTSPOTS.botanical, HOTSPOTS.lai_chi_kok, HOTSPOTS.kowloon_park, HOTSPOTS.hkpark, HOTSPOTS.victoria_park],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#8B4513', emoji: '🐦', call: '嗶—卡—嗶',
    tags: ['留鳥', '都市鳥'],
    aiRecognizable: true, aiConfidence: 0.91, merlinCode: 'revbul', ebirdCode: 'revbul',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-004', lastUpdated: Date.now(), pack: 1, source: 'internal',
  },
  {
    id: 5, name: '夜鷺', nameEn: 'Black-crowned Night Heron', nameYue: '夜游鶴', scientificName: 'Nycticorax nycticorax',
    family: '鷺科', familyEn: 'Ardeidae', order: '鵜形目',
    size: '58 cm', habitat: ['濕地'], diet: '魚、蝦',
    features: '頭頂黑、背部深灰、腹白',
    funFact: '夜鷺是夜貓子，晚上才出來抓魚！',
    description: '夜行性鷺鳥，俗稱「暗光鳥」。',
    region: '濕地', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.wetland, HOTSPOTS.namsangwai, HOTSPOTS.taipo_park, HOTSPOTS.longvalley],
    globalRange: ['全球除南極洲'],
    baseColor: '#4A5F7A', emoji: '🦩', call: '呱——',
    tags: ['留鳥', '夜行'],
    aiRecognizable: false, merlinCode: 'bcnher',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-005', lastUpdated: Date.now(), pack: 1, source: 'internal',
  },
  {
    id: 6, name: '小白鷺', nameEn: 'Little Egret', nameYue: '小白鷺', scientificName: 'Egretta garzetta',
    family: '鷺科', familyEn: 'Ardeidae', order: '鵜形目',
    size: '60 cm', habitat: ['濕地', '海岸'], diet: '魚、蝦',
    features: '全身雪白、腳趾鮮黃',
    funFact: '小白鷺的腳趾是黃色的，像穿了黃襪子！',
    description: '常單腳佇立水中獵食，優雅如舞者。',
    region: '濕地、海岸', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.sharp, HOTSPOTS.lantau, HOTSPOTS.wetland, HOTSPOTS.pakfu],
    globalRange: ['歐洲', '非洲', '亞洲', '大洋洲'],
    baseColor: '#F5F5F5', emoji: '🕊️', call: '嘎嘎',
    tags: ['留鳥', '水鳥'],
    aiRecognizable: true, aiConfidence: 0.93, merlinCode: 'litegr', ebirdCode: 'litegr',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-006', lastUpdated: Date.now(), pack: 1, source: 'internal',
  },
  {
    id: 7, name: '紅嘴藍鵲', nameEn: 'Red-billed Blue Magpie', nameYue: '長尾山娘', scientificName: 'Urocissa erythroryncha',
    family: '鴉科', familyEn: 'Corvidae', order: '雀形目',
    size: '68 cm', habitat: ['森林'], diet: '雜食',
    features: '藍色羽毛、紅嘴紅腳、長尾巴',
    funFact: '紅嘴藍鵲會成群出沒，尾巴超長像彩帶！',
    description: '東亞常見的鴉科鳥類，群居且聰明。',
    region: '郊野、山地', season: '四季',
    hotspots: [HOTSPOTS.luklampo, HOTSPOTS.taimoshan, HOTSPOTS.shingmun, HOTSPOTS.kadoorie, HOTSPOTS.lantau],
    globalRange: ['中國南部', '東南亞', '喜馬拉雅'],
    baseColor: '#4A7BC8', emoji: '🦚', call: '嘎嘎嘎！',
    tags: ['留鳥', '聰明鳥'],
    aiRecognizable: true, aiConfidence: 0.97, merlinCode: 'rebmag1', ebirdCode: 'rebmag1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-007', lastUpdated: Date.now(), pack: 1, source: 'internal',
  },
  {
    id: 8, name: '黑臉噪鶥', nameEn: 'Masked Laughingthrush', nameYue: '七姊妹', scientificName: 'Pterorhinus perspicillatus',
    family: '噪鶥科', familyEn: 'Leiothrichidae', order: '雀形目',
    size: '30 cm', habitat: ['森林', '公園'], diet: '雜食',
    features: '黑色眼罩、褐色身體',
    funFact: '黑臉噪鶥叫聲很響亮，常在樹叢中熱鬧地喊叫！',
    description: '群居鳥類，經常在地面翻動落葉找食物。',
    region: '公園、郊野', season: '四季',
    hotspots: [HOTSPOTS.kadoorie, HOTSPOTS.hkpark, HOTSPOTS.luklampo, HOTSPOTS.victoria_park, HOTSPOTS.botanical],
    globalRange: ['中國南部', '越南'],
    baseColor: '#6B4423', emoji: '🐦', call: '喳喳喳！',
    tags: ['留鳥', '群居'],
    aiRecognizable: true, aiConfidence: 0.86, merlinCode: 'maslau1', ebirdCode: 'maslau1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-008', lastUpdated: Date.now(), pack: 1, source: 'internal',
  },
  {
    id: 9, name: '黑鳶', nameEn: 'Black Kite', nameYue: '麻鷹', scientificName: 'Milvus migrans',
    family: '鷹科', familyEn: 'Accipitridae', order: '鷹形目',
    size: '65 cm', habitat: ['海岸', '市區'], diet: '腐肉、魚',
    features: '深褐羽毛、尾巴分叉、盤旋飛行',
    funFact: '黑鳶是香港的「麻鷹」，常在維港上空盤旋！',
    description: '香港最常見的猛禽，擅於利用氣流翱翔。',
    region: '沿海、市區', season: '四季',
    hotspots: [HOTSPOTS.central_pier, HOTSPOTS.harbour, HOTSPOTS.aberdeen, HOTSPOTS.peak, HOTSPOTS.tsimclock],
    globalRange: ['歐亞非澳'],
    baseColor: '#4A3728', emoji: '🦅', call: '咻—咻—',
    tags: ['猛禽', '都市'],
    aiRecognizable: true, aiConfidence: 0.88, merlinCode: 'blakit1', ebirdCode: 'blakit1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-009', lastUpdated: Date.now(), pack: 1, source: 'internal',
  },
  {
    id: 10, name: '黑臉琵鷺', nameEn: 'Black-faced Spoonbill', nameYue: '黑面琵鷺', scientificName: 'Platalea minor',
    family: '䴉科', familyEn: 'Threskiornithidae', order: '鵜形目',
    size: '76 cm', habitat: ['海岸', '濕地'], diet: '魚、蝦',
    features: '嘴巴像飯匙、黑色臉部、白色身體',
    funFact: '全球只剩約 6000 隻，香港是重要度冬地！',
    description: '全球瀕危鳥種，每年冬季飛抵后海灣度冬。',
    region: '后海灣', season: '冬季（11-3月）',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.sharp, HOTSPOTS.pakfu, HOTSPOTS.wetland, HOTSPOTS.namsangwai],
    globalRange: ['東亞'],
    baseColor: '#E8B84C', emoji: '🦢', call: '低沉鼻音',
    tags: ['冬候鳥', '瀕危', '明星鳥'],
    aiRecognizable: true, aiConfidence: 0.89, merlinCode: 'bfsp1', ebirdCode: 'bfsp1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-010', lastUpdated: Date.now(), pack: 1, source: 'internal',
  },
  {
    id: 11, name: '普通翠鳥', nameEn: 'Common Kingfisher', nameYue: '魚狗', scientificName: 'Alcedo atthis',
    family: '翠鳥科', familyEn: 'Alcedinidae', order: '佛法僧目',
    size: '16 cm', habitat: ['濕地', '溪流'], diet: '魚',
    features: '背羽寶藍、腹橙色、短尾',
    funFact: '翠鳥潛水抓魚超快，像一道藍色閃電！',
    description: '俗稱「魚狗」，潛水捕魚速度極快。',
    region: '濕地、溪流', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.luklampo, HOTSPOTS.wetland, HOTSPOTS.shingmun, HOTSPOTS.namsangwai],
    globalRange: ['歐亞非'],
    baseColor: '#4AA6C8', emoji: '🐦', call: '唰——',
    tags: ['留鳥', '溪流鳥'],
    aiRecognizable: true, aiConfidence: 0.94, merlinCode: 'coakin1', ebirdCode: 'coakin1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-011', lastUpdated: Date.now(), pack: 2, source: 'internal',
  },
  {
    id: 12, name: '黑枕王鶲', nameEn: 'Black-naped Monarch', nameYue: '藍背鶲', scientificName: 'Hypothymis azurea',
    family: '王鶲科', familyEn: 'Monarchidae', order: '雀形目',
    size: '16 cm', habitat: ['森林'], diet: '蟲',
    features: '雄鳥藍色、頭後黑斑',
    funFact: '雄鳥全身藍色，像會飛的小寶石！',
    description: '活潑於低海拔森林中層活動。',
    region: '郊野森林', season: '四季',
    hotspots: [HOTSPOTS.luklampo, HOTSPOTS.longfu, HOTSPOTS.taipo_kau, HOTSPOTS.kadoorie, HOTSPOTS.shingmun],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#7B8DD8', emoji: '🪽', call: '輝——輝——',
    tags: ['留鳥', '林鳥'],
    aiRecognizable: true, aiConfidence: 0.82, merlinCode: 'bnmfly2', ebirdCode: 'bnmfly2',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-012', lastUpdated: Date.now(), pack: 2, source: 'internal',
  },
  {
    id: 13, name: '紫嘯鶇', nameEn: 'Blue Whistling Thrush', nameYue: '紫嘯鶇', scientificName: 'Myophonus caeruleus',
    family: '鶇科', familyEn: 'Turdidae', order: '雀形目',
    size: '32 cm', habitat: ['山地', '溪流'], diet: '雜食',
    features: '全身深紫、金屬光澤',
    funFact: '叫聲像腳踏車煞車，超有特色！',
    description: '常於溪流附近活動，叫聲響亮。',
    region: '山澗', season: '四季',
    hotspots: [HOTSPOTS.luklampo, HOTSPOTS.shingmun, HOTSPOTS.taimoshan, HOTSPOTS.lantau, HOTSPOTS.fung_wong],
    globalRange: ['東亞', '東南亞'],
    baseColor: '#6B4F9E', emoji: '🐦', call: '尖銳哨音',
    tags: ['留鳥', '溪流鳥'],
    aiRecognizable: true, aiConfidence: 0.86, merlinCode: 'bluwhi1', ebirdCode: 'bluwhi1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-013', lastUpdated: Date.now(), pack: 2, source: 'internal',
  },
  {
    id: 14, name: '遠東山雀', nameEn: 'Cinereous Tit', nameYue: '灰山雀', scientificName: 'Parus cinereus',
    family: '山雀科', familyEn: 'Paridae', order: '雀形目',
    size: '14 cm', habitat: ['森林', '公園'], diet: '蟲',
    features: '黑頭白頰、胸腹黑條紋',
    funFact: '山雀頭上像戴了一頂黑色小圓帽！',
    description: '活潑的小型鳥，常於樹梢跳躍啄食。',
    region: '全港公園、郊野', season: '四季',
    hotspots: [HOTSPOTS.kowloon_park, HOTSPOTS.kadoorie, HOTSPOTS.luklampo, HOTSPOTS.hkpark, HOTSPOTS.shingmun],
    globalRange: ['南亞', '東亞'],
    baseColor: '#333333', emoji: '🐤', call: '吱—吱—',
    tags: ['留鳥', '小型鳥'],
    aiRecognizable: true, aiConfidence: 0.85, merlinCode: 'cintit2', ebirdCode: 'cintit2',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-014', lastUpdated: Date.now(), pack: 2, source: 'internal',
  },
  {
    id: 15, name: '珠頸斑鳩', nameEn: 'Spotted Dove', nameYue: '斑鳩', scientificName: 'Spilopelia chinensis',
    family: '鳩鴿科', familyEn: 'Columbidae', order: '鴿形目',
    size: '30 cm', habitat: ['都市', '公園'], diet: '種子',
    features: '頸後黑底白點、粉灰色身體',
    funFact: '珠頸斑鳩脖子後面有一串白色珍珠項鍊！',
    description: '常見都市鳥，叫聲低沉規律「咕—咕咕—」。',
    region: '全港', season: '四季',
    hotspots: [HOTSPOTS.victoria_park, HOTSPOTS.kowloon_park, HOTSPOTS.shatin, HOTSPOTS.hkpark, HOTSPOTS.lai_chi_kok],
    globalRange: ['東亞', '東南亞'],
    baseColor: '#A89B8A', emoji: '🕊️', call: '咕—咕咕—',
    tags: ['留鳥', '都市鳥'],
    aiRecognizable: true, aiConfidence: 0.93, merlinCode: 'spodov', ebirdCode: 'spodov',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-015', lastUpdated: Date.now(), pack: 2, source: 'internal',
  },
  {
    id: 16, name: '八哥', nameEn: 'Crested Myna', nameYue: '鷯哥', scientificName: 'Acridotheres cristatellus',
    family: '椋鳥科', familyEn: 'Sturnidae', order: '雀形目',
    size: '26 cm', habitat: ['都市', '鄉村'], diet: '雜食',
    features: '全身黑亮、額前羽冠、黃色嘴腳',
    funFact: '八哥可以學人說話，是很聰明的小朋友！',
    description: '聰明的都市鳥，能模仿各種聲音。',
    region: '全港', season: '四季',
    hotspots: [HOTSPOTS.lai_chi_kok, HOTSPOTS.botanical, HOTSPOTS.victoria_park, HOTSPOTS.hkpark, HOTSPOTS.kln_tsai],
    globalRange: ['中國南部', '東南亞'],
    baseColor: '#1A1A1A', emoji: '🐦', call: '嗒—嗒—',
    tags: ['留鳥', '聰明鳥'],
    aiRecognizable: true, aiConfidence: 0.89, merlinCode: 'cremyn', ebirdCode: 'cremyn',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-016', lastUpdated: Date.now(), pack: 2, source: 'internal',
  },
  {
    id: 17, name: '家燕', nameEn: 'Barn Swallow', nameYue: '燕仔', scientificName: 'Hirundo rustica',
    family: '燕科', familyEn: 'Hirundinidae', order: '雀形目',
    size: '17 cm', habitat: ['都市', '鄉村'], diet: '飛蟲',
    features: '藍黑上身、紅喉、叉狀尾',
    funFact: '家燕會在屋簷下築巢，是人類的好鄰居！',
    description: '夏候鳥，空中捕食飛蟲，築碗狀泥巢。',
    region: '全港', season: '春夏',
    hotspots: [HOTSPOTS.tsimclock, HOTSPOTS.yuen_long, HOTSPOTS.shatin, HOTSPOTS.kowloon_park, HOTSPOTS.cheung_chau],
    globalRange: ['全球除南極洲'],
    baseColor: '#2B3F5F', emoji: '🐦', call: '唧哩唧哩',
    tags: ['夏候鳥'],
    aiRecognizable: true, aiConfidence: 0.87, merlinCode: 'barswa', ebirdCode: 'barswa',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-017', lastUpdated: Date.now(), pack: 2, source: 'internal',
  },
  {
    id: 18, name: '黑卷尾', nameEn: 'Black Drongo', nameYue: '烏秋', scientificName: 'Dicrurus macrocercus',
    family: '卷尾科', familyEn: 'Dicruridae', order: '雀形目',
    size: '29 cm', habitat: ['鄉村', '田野'], diet: '昆蟲',
    features: '全身黑亮、尾巴分叉卷曲',
    funFact: '黑卷尾很勇敢，會驅趕比牠大的鳥！',
    description: '俗稱「烏秋」，常停於電線或牛背上。',
    region: '新界鄉郊', season: '四季',
    hotspots: [HOTSPOTS.namsangwai, HOTSPOTS.taipo_park, HOTSPOTS.longvalley, HOTSPOTS.yuen_long, HOTSPOTS.sharp],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#1A1A1A', emoji: '🪶', call: '嘰—啾',
    tags: ['留鳥', '平原鳥'],
    aiRecognizable: true, aiConfidence: 0.89, merlinCode: 'bladro1', ebirdCode: 'bladro1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-018', lastUpdated: Date.now(), pack: 2, source: 'internal',
  },
  {
    id: 19, name: '白腰文鳥', nameEn: 'White-rumped Munia', nameYue: '白腰文鳥', scientificName: 'Lonchura striata',
    family: '梅花雀科', familyEn: 'Estrildidae', order: '雀形目',
    size: '11 cm', habitat: ['草原', '鄉村'], diet: '草籽',
    features: '褐色身體、白色腰部',
    funFact: '白腰文鳥喜歡成群結隊，像一團小毛球！',
    description: '小型草原鳥類，常於草叢中覓食草籽。',
    region: '鄉郊', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.longvalley, HOTSPOTS.namsangwai, HOTSPOTS.sharp, HOTSPOTS.taipo_park],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#8B6F47', emoji: '🐦', call: '啾啾',
    tags: ['留鳥', '群居'],
    aiRecognizable: true, aiConfidence: 0.84, merlinCode: 'whrmun', ebirdCode: 'whrmun',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-019', lastUpdated: Date.now(), pack: 2, source: 'internal',
  },
  {
    id: 20, name: '牛背鷺', nameEn: 'Cattle Egret', nameYue: '黃頭鷺', scientificName: 'Bubulcus ibis',
    family: '鷺科', familyEn: 'Ardeidae', order: '鵜形目',
    size: '50 cm', habitat: ['草原', '農地'], diet: '昆蟲',
    features: '繁殖期頭胸背金黃',
    funFact: '牛背鷺常站在水牛背上吃驚飛的蟲！',
    description: '又稱「黃頭鷺」，常與放牧動物共生。',
    region: '鄉郊、濕地', season: '四季',
    hotspots: [HOTSPOTS.longvalley, HOTSPOTS.maipo, HOTSPOTS.namsangwai, HOTSPOTS.sharp, HOTSPOTS.pakfu],
    globalRange: ['全球除南極洲'],
    baseColor: '#EED688', emoji: '🕊️', call: '啞啞',
    tags: ['留鳥', '水鳥'],
    aiRecognizable: true, aiConfidence: 0.90, merlinCode: 'categr', ebirdCode: 'categr',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-020', lastUpdated: Date.now(), pack: 2, source: 'internal',
  },
  {
    id: 21, name: '黃腹鷦鶯', nameEn: 'Yellow-bellied Prinia', nameYue: '黃腹鷦鶯', scientificName: 'Prinia flaviventris',
    family: '扇尾鶯科', familyEn: 'Cisticolidae', order: '雀形目',
    size: '13 cm', habitat: ['草原', '濕地'], diet: '蟲',
    features: '上身橄欖綠、腹部鮮黃',
    funFact: '黃腹鷦鶯尾巴總是翹得高高的，超可愛！',
    description: '小型鳴禽，常於草叢頂端唱歌。',
    region: '鄉郊草地', season: '四季',
    hotspots: [HOTSPOTS.namsangwai, HOTSPOTS.longvalley, HOTSPOTS.maipo, HOTSPOTS.sharp, HOTSPOTS.wetland],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#C9A83E', emoji: '🐦', call: '吱—吱—',
    tags: ['留鳥', '草原鳥'],
    aiRecognizable: true, aiConfidence: 0.81, merlinCode: 'yebpri', ebirdCode: 'yebpri',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-021', lastUpdated: Date.now(), pack: 3, source: 'internal',
  },
  {
    id: 22, name: '白胸苦惡鳥', nameEn: 'White-breasted Waterhen', nameYue: '苦惡鳥', scientificName: 'Amaurornis phoenicurus',
    family: '秧雞科', familyEn: 'Rallidae', order: '鶴形目',
    size: '32 cm', habitat: ['濕地', '溪流'], diet: '雜食',
    features: '白色臉胸、深褐背部',
    funFact: '叫聲聽起來像「苦啊—苦啊—」故得名！',
    description: '秧雞科鳥類，活動於濕地邊緣。',
    region: '濕地', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.wetland, HOTSPOTS.namsangwai, HOTSPOTS.longvalley, HOTSPOTS.taipo_kau],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#5A4A3A', emoji: '🐦', call: '苦啊—苦啊—',
    tags: ['留鳥', '濕地'],
    aiRecognizable: true, aiConfidence: 0.85, merlinCode: 'whbwat1', ebirdCode: 'whbwat1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-022', lastUpdated: Date.now(), pack: 3, source: 'internal',
  },
  {
    id: 23, name: '小鸊鷉', nameEn: 'Little Grebe', nameYue: '水葫蘆', scientificName: 'Tachybaptus ruficollis',
    family: '鸊鷉科', familyEn: 'Podicipedidae', order: '鸊鷉目',
    size: '27 cm', habitat: ['濕地', '池塘'], diet: '魚',
    features: '圓胖褐色身體、紅褐頸部',
    funFact: '小鸊鷉潛水超厲害，像個小潛水艇！',
    description: '常於池塘水面浮游，受驚會快速潛水。',
    region: '池塘、魚塘', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.namsangwai, HOTSPOTS.wetland, HOTSPOTS.longvalley, HOTSPOTS.taipo_park],
    globalRange: ['歐亞非'],
    baseColor: '#7D5A3A', emoji: '🦆', call: '咯咯咯',
    tags: ['留鳥', '水鳥'],
    aiRecognizable: true, aiConfidence: 0.83, merlinCode: 'litgre1', ebirdCode: 'litgre1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-023', lastUpdated: Date.now(), pack: 3, source: 'internal',
  },
  {
    id: 24, name: '領角鴞', nameEn: 'Collared Scops Owl', nameYue: '貓頭鷹', scientificName: 'Otus lettia',
    family: '鴟鴞科', familyEn: 'Strigidae', order: '鴞形目',
    size: '24 cm', habitat: ['森林'], diet: '昆蟲、小動物',
    features: '灰褐羽毛、耳羽突出、黃色眼睛',
    funFact: '領角鴞是香港的小型貓頭鷹，超可愛！',
    description: '夜行性貓頭鷹，白天躲在樹洞裡睡覺。',
    region: '郊野林地', season: '四季',
    hotspots: [HOTSPOTS.luklampo, HOTSPOTS.kadoorie, HOTSPOTS.shingmun, HOTSPOTS.taimoshan, HOTSPOTS.longfu],
    globalRange: ['南亞', '東亞', '東南亞'],
    baseColor: '#8B7355', emoji: '🦉', call: '嗚—嗚—',
    tags: ['夜行', '猛禽'],
    aiRecognizable: false, merlinCode: 'colsco1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-024', lastUpdated: Date.now(), pack: 3, source: 'internal',
  },
  {
    id: 25, name: '灰喉山椒鳥', nameEn: 'Grey-chinned Minivet', nameYue: '山椒鳥', scientificName: 'Pericrocotus solaris',
    family: '山椒鳥科', familyEn: 'Campephagidae', order: '雀形目',
    size: '18 cm', habitat: ['森林'], diet: '昆蟲',
    features: '雄鳥橘紅色、雌鳥黃色',
    funFact: '山椒鳥雄雌顏色不同，一紅一黃像情侶裝！',
    description: '成對或成群活動於森林中上層。',
    region: '郊野森林', season: '四季',
    hotspots: [HOTSPOTS.luklampo, HOTSPOTS.taimoshan, HOTSPOTS.kadoorie, HOTSPOTS.shingmun, HOTSPOTS.longfu],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#E85A2B', emoji: '🦜', call: '啼—啼—',
    tags: ['留鳥', '林鳥'],
    aiRecognizable: true, aiConfidence: 0.86, merlinCode: 'gcmmin1', ebirdCode: 'gcmmin1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-025', lastUpdated: Date.now(), pack: 3, source: 'internal',
  },
  {
    id: 26, name: '青背山雀', nameEn: 'Green-backed Tit', nameYue: '青背山雀', scientificName: 'Parus monticolus',
    family: '山雀科', familyEn: 'Paridae', order: '雀形目',
    size: '13 cm', habitat: ['森林'], diet: '蟲',
    features: '背部青綠、腹部鮮黃',
    funFact: '青背山雀活潑好動，常於樹梢啄食小蟲！',
    description: '中海拔的小精靈，色彩鮮豔活潑。',
    region: '高地', season: '四季',
    hotspots: [HOTSPOTS.taimoshan, HOTSPOTS.fung_wong, HOTSPOTS.lantau, HOTSPOTS.luklampo, HOTSPOTS.shingmun],
    globalRange: ['喜馬拉雅', '東亞'],
    baseColor: '#0891B2', emoji: '🐤', call: '吱——吱——',
    tags: ['留鳥'],
    aiRecognizable: true, aiConfidence: 0.85, merlinCode: 'grbtit1', ebirdCode: 'grbtit1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-026', lastUpdated: Date.now(), pack: 3, source: 'internal',
  },
  {
    id: 27, name: '紅尾伯勞', nameEn: 'Brown Shrike', nameYue: '伯勞', scientificName: 'Lanius cristatus',
    family: '伯勞科', familyEn: 'Laniidae', order: '雀形目',
    size: '20 cm', habitat: ['草原'], diet: '肉食',
    features: '過眼線黑、尾紅褐',
    funFact: '紅尾伯勞會把獵物串在樹枝上儲存，被叫「屠夫鳥」！',
    description: '冬候鳥，有刺獵物於樹枝儲存的習性。',
    region: '鄉郊', season: '冬季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.longvalley, HOTSPOTS.namsangwai, HOTSPOTS.sharp, HOTSPOTS.taipo_park],
    globalRange: ['東亞', '東南亞'],
    baseColor: '#B91C1C', emoji: '🪶', call: '嘎——嘎——',
    tags: ['冬候鳥', '肉食'],
    aiRecognizable: true, aiConfidence: 0.87, merlinCode: 'brnshr', ebirdCode: 'brnshr',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-027', lastUpdated: Date.now(), pack: 3, source: 'internal',
  },
  {
    id: 28, name: '北紅尾鴝', nameEn: 'Daurian Redstart', nameYue: '北紅尾鴝', scientificName: 'Phoenicurus auroreus',
    family: '鶲科', familyEn: 'Muscicapidae', order: '雀形目',
    size: '15 cm', habitat: ['草原', '公園'], diet: '蟲',
    features: '雄鳥腹尾鮮橙',
    funFact: '北紅尾鴝冬天從北方飛來，春天才回家！',
    description: '冬候鳥，雄鳥橙腹鮮豔，常停於開闊地。',
    region: '公園、郊野', season: '冬季',
    hotspots: [HOTSPOTS.victoria_park, HOTSPOTS.taipo_park, HOTSPOTS.kowloon_park, HOTSPOTS.hkpark, HOTSPOTS.shatin],
    globalRange: ['東亞'],
    baseColor: '#F59E0B', emoji: '🐦', call: '嗒嗒嗒',
    tags: ['冬候鳥'],
    aiRecognizable: true, aiConfidence: 0.83, merlinCode: 'daured1', ebirdCode: 'daured1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-028', lastUpdated: Date.now(), pack: 3, source: 'internal',
  },
  {
    id: 29, name: '白鶺鴒', nameEn: 'White Wagtail', nameYue: '白鶺鴒', scientificName: 'Motacilla alba',
    family: '鶺鴒科', familyEn: 'Motacillidae', order: '雀形目',
    size: '18 cm', habitat: ['濕地', '市區'], diet: '蟲',
    features: '黑白相間、長尾不停擺動',
    funFact: '白鶺鴒走路時尾巴會一直上下擺動！',
    description: '常見於水邊，走路時尾巴不停擺動。',
    region: '全港', season: '冬季',
    hotspots: [HOTSPOTS.harbour, HOTSPOTS.maipo, HOTSPOTS.central_pier, HOTSPOTS.taipo_park, HOTSPOTS.aberdeen],
    globalRange: ['歐亞非'],
    baseColor: '#2C2C2C', emoji: '🐦', call: '唧唧',
    tags: ['冬候鳥'],
    aiRecognizable: true, aiConfidence: 0.90, merlinCode: 'whiwag', ebirdCode: 'whiwag',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-029', lastUpdated: Date.now(), pack: 3, source: 'internal',
  },
  {
    id: 30, name: '普通鸕鶿', nameEn: 'Great Cormorant', nameYue: '鸕鶿', scientificName: 'Phalacrocorax carbo',
    family: '鸕鶿科', familyEn: 'Phalacrocoracidae', order: '鰹鳥目',
    size: '90 cm', habitat: ['海岸', '濕地'], diet: '魚',
    features: '全身深黑、長頸、鉤狀嘴',
    funFact: '鸕鶿潛水超厲害，一次可以抓好幾條魚！',
    description: '大型水鳥，擅於潛水捕魚，常群體覓食。',
    region: '后海灣、海岸', season: '冬季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.pakfu, HOTSPOTS.sharp, HOTSPOTS.wetland, HOTSPOTS.aberdeen],
    globalRange: ['全球除南極'],
    baseColor: '#1A1A1A', emoji: '🦅', call: '咯咯',
    tags: ['冬候鳥', '水鳥'],
    aiRecognizable: true, aiConfidence: 0.88, merlinCode: 'grecor', ebirdCode: 'grecor',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-030', lastUpdated: Date.now(), pack: 3, source: 'internal',
  },
  // ========== Pack 4: 水鳥與海鳥 ==========
  {
    id: 31, name: '普通燕鷗', nameEn: 'Common Tern', nameYue: '燕鷗', scientificName: 'Sterna hirundo',
    family: '鷗科', familyEn: 'Laridae', order: '鴴形目',
    size: '35 cm', habitat: ['海岸'], diet: '魚',
    features: '白身黑頂、紅嘴、分叉尾',
    funFact: '燕鷗會俯衝入水捕魚，像小型轟炸機！',
    description: '夏候鳥，於離島礁石築巢。',
    region: '離島海域', season: '春夏',
    hotspots: [HOTSPOTS.cheung_chau, HOTSPOTS.lamma, HOTSPOTS.aberdeen, HOTSPOTS.harbour, HOTSPOTS.lantau],
    globalRange: ['全球除南極'],
    baseColor: '#A0A0A0', emoji: '🕊️', call: '嘰嘎',
    tags: ['夏候鳥', '海鳥'],
    aiRecognizable: true, aiConfidence: 0.86, merlinCode: 'comter', ebirdCode: 'comter',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-031', lastUpdated: Date.now(), pack: 4, source: 'internal',
  },
  {
    id: 32, name: '紅腳鷸', nameEn: 'Common Redshank', nameYue: '紅腳鷸', scientificName: 'Tringa totanus',
    family: '鷸科', familyEn: 'Scolopacidae', order: '鴴形目',
    size: '28 cm', habitat: ['濕地', '泥灘'], diet: '無脊椎動物',
    features: '鮮紅色長腿、灰褐身體',
    funFact: '紅腳鷸的紅腳像穿了紅色小靴子！',
    description: '冬候鳥，常於泥灘尋找食物。',
    region: '后海灣', season: '冬季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.sharp, HOTSPOTS.pakfu, HOTSPOTS.wetland, HOTSPOTS.lantau],
    globalRange: ['歐亞非'],
    baseColor: '#B91C1C', emoji: '🐦', call: '嘀—嘀—',
    tags: ['冬候鳥', '水鳥'],
    aiRecognizable: true, aiConfidence: 0.82, merlinCode: 'comred1', ebirdCode: 'comred1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-032', lastUpdated: Date.now(), pack: 4, source: 'internal',
  },
  {
    id: 33, name: '反嘴鷸', nameEn: 'Pied Avocet', nameYue: '反嘴鷸', scientificName: 'Recurvirostra avosetta',
    family: '反嘴鷸科', familyEn: 'Recurvirostridae', order: '鴴形目',
    size: '43 cm', habitat: ['濕地'], diet: '蝦、無脊椎動物',
    features: '黑白分明、嘴向上翹',
    funFact: '反嘴鷸的嘴向上彎，像一把小小的鐮刀！',
    description: '冬候鳥，於淺灘左右掃動嘴巴覓食。',
    region: '后海灣', season: '冬季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.sharp, HOTSPOTS.wetland, HOTSPOTS.pakfu, HOTSPOTS.namsangwai],
    globalRange: ['歐亞非'],
    baseColor: '#F5F5F5', emoji: '🕊️', call: '咯—咯—',
    tags: ['冬候鳥', '水鳥'],
    aiRecognizable: true, aiConfidence: 0.88, merlinCode: 'piavoc', ebirdCode: 'piavoc',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-033', lastUpdated: Date.now(), pack: 4, source: 'internal',
  },
  {
    id: 34, name: '蒼鷺', nameEn: 'Grey Heron', nameYue: '蒼鷺', scientificName: 'Ardea cinerea',
    family: '鷺科', familyEn: 'Ardeidae', order: '鵜形目',
    size: '100 cm', habitat: ['濕地'], diet: '魚',
    features: '灰色身體、S 型頸、長腿',
    funFact: '蒼鷺站著不動等魚游過，是個耐心獵人！',
    description: '大型鷺鳥，常靜立水邊等待獵物。',
    region: '濕地', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.wetland, HOTSPOTS.namsangwai, HOTSPOTS.longvalley, HOTSPOTS.sharp],
    globalRange: ['歐亞非'],
    baseColor: '#7A8394', emoji: '🦩', call: '嘎—',
    tags: ['留鳥', '水鳥'],
    aiRecognizable: true, aiConfidence: 0.92, merlinCode: 'greher1', ebirdCode: 'greher1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-034', lastUpdated: Date.now(), pack: 4, source: 'internal',
  },
  {
    id: 35, name: '大白鷺', nameEn: 'Great Egret', nameYue: '大白鷺', scientificName: 'Ardea alba',
    family: '鷺科', familyEn: 'Ardeidae', order: '鵜形目',
    size: '90 cm', habitat: ['濕地'], diet: '魚',
    features: '全身純白、長頸長嘴',
    funFact: '大白鷺是香港最大的白鷺！',
    description: '全身雪白的大型鷺鳥，優雅獵食。',
    region: '濕地', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.wetland, HOTSPOTS.sharp, HOTSPOTS.longvalley, HOTSPOTS.pakfu],
    globalRange: ['全球'],
    baseColor: '#FFFFFF', emoji: '🕊️', call: '嘎嘎',
    tags: ['留鳥', '水鳥'],
    aiRecognizable: true, aiConfidence: 0.94, merlinCode: 'greegr', ebirdCode: 'greegr',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-035', lastUpdated: Date.now(), pack: 4, source: 'internal',
  },
  {
    id: 36, name: '紅頭咬鵑', nameEn: 'Red-headed Trogon', nameYue: '紅頭咬鵑', scientificName: 'Harpactes erythrocephalus',
    family: '咬鵑科', familyEn: 'Trogonidae', order: '咬鵑目',
    size: '33 cm', habitat: ['森林'], diet: '昆蟲、果實',
    features: '紅頭綠背、尾部白斑',
    funFact: '紅頭咬鵑色彩鮮豔，是香港森林的寶石！',
    description: '罕見留鳥，常於原始森林內活動。',
    region: '郊野森林', season: '四季',
    hotspots: [HOTSPOTS.taimoshan, HOTSPOTS.shingmun, HOTSPOTS.luklampo, HOTSPOTS.kadoorie, HOTSPOTS.fung_wong],
    globalRange: ['東亞', '東南亞'],
    baseColor: '#DC2626', emoji: '🦜', call: '咕——咕——',
    tags: ['留鳥', '稀有'],
    aiRecognizable: true, aiConfidence: 0.78, merlinCode: 'rehtro1', ebirdCode: 'rehtro1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-036', lastUpdated: Date.now(), pack: 4, source: 'internal',
  },
  {
    id: 37, name: '棕背伯勞', nameEn: 'Long-tailed Shrike', nameYue: '伯勞', scientificName: 'Lanius schach',
    family: '伯勞科', familyEn: 'Laniidae', order: '雀形目',
    size: '25 cm', habitat: ['草原'], diet: '肉食',
    features: '棕褐色背、黑色過眼線',
    funFact: '棕背伯勞尾巴很長，常在電線上監視獵物！',
    description: '平原上的小型猛禽，視力極佳。',
    region: '鄉郊', season: '四季',
    hotspots: [HOTSPOTS.longvalley, HOTSPOTS.namsangwai, HOTSPOTS.maipo, HOTSPOTS.yuen_long, HOTSPOTS.taipo_park],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#92400E', emoji: '🪶', call: '喳—喳—',
    tags: ['留鳥', '肉食'],
    aiRecognizable: true, aiConfidence: 0.85, merlinCode: 'lotshr1', ebirdCode: 'lotshr1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-037', lastUpdated: Date.now(), pack: 4, source: 'internal',
  },
  {
    id: 38, name: '黃胸織雀', nameEn: 'Baya Weaver', nameYue: '織布鳥', scientificName: 'Ploceus philippinus',
    family: '織布鳥科', familyEn: 'Ploceidae', order: '雀形目',
    size: '15 cm', habitat: ['草原'], diet: '種子',
    features: '雄鳥繁殖期頭頂金黃',
    funFact: '織布鳥會編織像布袋的鳥巢，超厲害！',
    description: '擅於編織複雜鳥巢，集體繁殖。',
    region: '鄉郊', season: '春夏',
    hotspots: [HOTSPOTS.longvalley, HOTSPOTS.maipo, HOTSPOTS.namsangwai, HOTSPOTS.yuen_long, HOTSPOTS.taipo_park],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#EAB308', emoji: '🐤', call: '啾啾',
    tags: ['留鳥', '繁殖期'],
    aiRecognizable: true, aiConfidence: 0.80, merlinCode: 'bayawe1', ebirdCode: 'bayawe1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-038', lastUpdated: Date.now(), pack: 4, source: 'internal',
  },
  {
    id: 39, name: '小鷿鷈', nameEn: 'Little Ringed Plover', nameYue: '小環頸鴴', scientificName: 'Charadrius dubius',
    family: '鴴科', familyEn: 'Charadriidae', order: '鴴形目',
    size: '16 cm', habitat: ['濕地'], diet: '無脊椎動物',
    features: '黑色頸圈、黃眼圈',
    funFact: '小鷿鷈跑步超快，在泥灘上跑來跑去！',
    description: '小型鴴鳥，於泥灘奔跑覓食。',
    region: '濕地、魚塘', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.longvalley, HOTSPOTS.namsangwai, HOTSPOTS.sharp, HOTSPOTS.wetland],
    globalRange: ['歐亞非'],
    baseColor: '#A0A0A0', emoji: '🐦', call: '嘀—嘀—',
    tags: ['水鳥', '小型'],
    aiRecognizable: true, aiConfidence: 0.79, merlinCode: 'lirplo', ebirdCode: 'lirplo',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-039', lastUpdated: Date.now(), pack: 4, source: 'internal',
  },
  {
    id: 40, name: '黃葦鷺', nameEn: 'Yellow Bittern', nameYue: '黃葦鷺', scientificName: 'Ixobrychus sinensis',
    family: '鷺科', familyEn: 'Ardeidae', order: '鵜形目',
    size: '36 cm', habitat: ['濕地', '蘆葦'], diet: '魚、青蛙',
    features: '黃褐色、翼尖黑',
    funFact: '黃葦鷺躲在蘆葦叢中像隱形忍者！',
    description: '常於蘆葦叢中活動，不易察覺。',
    region: '濕地', season: '春夏',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.wetland, HOTSPOTS.longvalley, HOTSPOTS.namsangwai, HOTSPOTS.sharp],
    globalRange: ['東亞', '東南亞'],
    baseColor: '#D4A054', emoji: '🦩', call: '呱呱',
    tags: ['夏候鳥', '濕地'],
    aiRecognizable: true, aiConfidence: 0.80, merlinCode: 'yebbit', ebirdCode: 'yebbit',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-040', lastUpdated: Date.now(), pack: 4, source: 'internal',
  },
  // ========== Pack 5: 特色鳥類 ==========
  {
    id: 41, name: '戴勝', nameEn: 'Eurasian Hoopoe', nameYue: '戴勝', scientificName: 'Upupa epops',
    family: '戴勝科', familyEn: 'Upupidae', order: '犀鳥目',
    size: '30 cm', habitat: ['草原'], diet: '昆蟲',
    features: '頭頂扇形冠羽、橙褐色身體',
    funFact: '戴勝頭上的冠羽像印第安人的頭飾！',
    description: '色彩特殊的鳥類，常張開扇形冠羽。',
    region: '鄉郊', season: '過境',
    hotspots: [HOTSPOTS.longvalley, HOTSPOTS.maipo, HOTSPOTS.namsangwai, HOTSPOTS.yuen_long, HOTSPOTS.taipo_park],
    globalRange: ['歐亞非'],
    baseColor: '#DC7633', emoji: '🦜', call: '嘀—嘀—嘀',
    tags: ['過境鳥', '特色'],
    aiRecognizable: true, aiConfidence: 0.91, merlinCode: 'eurhoo1', ebirdCode: 'eurhoo1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-041', lastUpdated: Date.now(), pack: 5, source: 'internal',
  },
  {
    id: 42, name: '紅胸啄花鳥', nameEn: 'Fire-breasted Flowerpecker', nameYue: '啄花鳥', scientificName: 'Dicaeum ignipectus',
    family: '啄花鳥科', familyEn: 'Dicaeidae', order: '雀形目',
    size: '9 cm', habitat: ['森林'], diet: '花蜜、小果',
    features: '雄鳥胸部火紅、背部深藍',
    funFact: '啄花鳥是香港最細小的鳥之一，比你手指還小！',
    description: '極小型鳥，活躍於花叢間吸食花蜜。',
    region: '郊野森林', season: '四季',
    hotspots: [HOTSPOTS.taimoshan, HOTSPOTS.luklampo, HOTSPOTS.shingmun, HOTSPOTS.kadoorie, HOTSPOTS.fung_wong],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#DC2626', emoji: '🐤', call: '嗞—嗞—',
    tags: ['留鳥', '小型'],
    aiRecognizable: true, aiConfidence: 0.78, merlinCode: 'fibflo1', ebirdCode: 'fibflo1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-042', lastUpdated: Date.now(), pack: 5, source: 'internal',
  },
  {
    id: 43, name: '黃腰柳鶯', nameEn: 'Pallas\'s Leaf Warbler', nameYue: '黃腰柳鶯', scientificName: 'Phylloscopus proregulus',
    family: '柳鶯科', familyEn: 'Phylloscopidae', order: '雀形目',
    size: '9 cm', habitat: ['森林'], diet: '蟲',
    features: '橄欖綠身體、腰部黃色',
    funFact: '柳鶯體型迷你，叫聲高亢像小鈴鐺！',
    description: '冬候鳥，活躍於樹冠層覓食。',
    region: '郊野', season: '冬季',
    hotspots: [HOTSPOTS.luklampo, HOTSPOTS.kadoorie, HOTSPOTS.shingmun, HOTSPOTS.hkpark, HOTSPOTS.botanical],
    globalRange: ['歐亞'],
    baseColor: '#65A30D', emoji: '🐤', call: '嘰—嘰—',
    tags: ['冬候鳥', '小型'],
    aiRecognizable: true, aiConfidence: 0.75, merlinCode: 'palwar1', ebirdCode: 'palwar1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-043', lastUpdated: Date.now(), pack: 5, source: 'internal',
  },
  {
    id: 44, name: '喜鵲', nameEn: 'Oriental Magpie', nameYue: '喜鵲', scientificName: 'Pica serica',
    family: '鴉科', familyEn: 'Corvidae', order: '雀形目',
    size: '46 cm', habitat: ['都市', '郊野'], diet: '雜食',
    features: '黑白分明、長尾巴',
    funFact: '喜鵲是鳥中聰明代表，能認識自己的鏡像！',
    description: '聰明的鴉科鳥類，適應力強。',
    region: '新界', season: '四季',
    hotspots: [HOTSPOTS.longvalley, HOTSPOTS.namsangwai, HOTSPOTS.yuen_long, HOTSPOTS.taipo_park, HOTSPOTS.kadoorie],
    globalRange: ['東亞'],
    baseColor: '#1F2937', emoji: '🦅', call: '喳喳喳',
    tags: ['留鳥', '聰明鳥'],
    aiRecognizable: true, aiConfidence: 0.91, merlinCode: 'orimag', ebirdCode: 'orimag',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-044', lastUpdated: Date.now(), pack: 5, source: 'internal',
  },
  {
    id: 45, name: '大杜鵑', nameEn: 'Common Cuckoo', nameYue: '布穀', scientificName: 'Cuculus canorus',
    family: '杜鵑科', familyEn: 'Cuculidae', order: '鵑形目',
    size: '33 cm', habitat: ['森林'], diet: '昆蟲',
    features: '灰色上身、腹部橫紋',
    funFact: '大杜鵑會把蛋下在別人巢裡，讓別人幫忙養小孩！',
    description: '夏候鳥，以「布穀、布穀」叫聲聞名。',
    region: '郊野', season: '春夏',
    hotspots: [HOTSPOTS.luklampo, HOTSPOTS.taimoshan, HOTSPOTS.shingmun, HOTSPOTS.kadoorie, HOTSPOTS.fung_wong],
    globalRange: ['歐亞非'],
    baseColor: '#6B7280', emoji: '🪶', call: '布—穀—',
    tags: ['夏候鳥', '寄生繁殖'],
    aiRecognizable: true, aiConfidence: 0.85, merlinCode: 'comcuc', ebirdCode: 'comcuc',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-045', lastUpdated: Date.now(), pack: 5, source: 'internal',
  },
  {
    id: 46, name: '鳳頭鷹', nameEn: 'Crested Goshawk', nameYue: '鳳頭鷹', scientificName: 'Accipiter trivirgatus',
    family: '鷹科', familyEn: 'Accipitridae', order: '鷹形目',
    size: '45 cm', habitat: ['森林'], diet: '肉食',
    features: '頭頂冠羽、灰褐色身體',
    funFact: '鳳頭鷹會躲在樹冠層突襲小鳥！',
    description: '中型猛禽，森林的隱形獵手。',
    region: '郊野森林', season: '四季',
    hotspots: [HOTSPOTS.taimoshan, HOTSPOTS.luklampo, HOTSPOTS.shingmun, HOTSPOTS.kadoorie, HOTSPOTS.lantau],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#78350F', emoji: '🦅', call: '咻—咻—',
    tags: ['猛禽', '留鳥'],
    aiRecognizable: false, merlinCode: 'cregos1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-046', lastUpdated: Date.now(), pack: 5, source: 'internal',
  },
  {
    id: 47, name: '斑文鳥', nameEn: 'Scaly-breasted Munia', nameYue: '斑文鳥', scientificName: 'Lonchura punctulata',
    family: '梅花雀科', familyEn: 'Estrildidae', order: '雀形目',
    size: '12 cm', habitat: ['草原'], diet: '草籽',
    features: '褐色背、胸腹鱗狀斑紋',
    funFact: '斑文鳥胸前有像魚鱗的花紋！',
    description: '小型草原鳥，常成群活動。',
    region: '鄉郊', season: '四季',
    hotspots: [HOTSPOTS.longvalley, HOTSPOTS.namsangwai, HOTSPOTS.maipo, HOTSPOTS.yuen_long, HOTSPOTS.taipo_park],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#92400E', emoji: '🐦', call: '啾啾',
    tags: ['留鳥', '群居'],
    aiRecognizable: true, aiConfidence: 0.83, merlinCode: 'scbmun', ebirdCode: 'scbmun',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-047', lastUpdated: Date.now(), pack: 5, source: 'internal',
  },
  {
    id: 48, name: '白胸翡翠', nameEn: 'White-throated Kingfisher', nameYue: '魚狗', scientificName: 'Halcyon smyrnensis',
    family: '翠鳥科', familyEn: 'Alcedinidae', order: '佛法僧目',
    size: '28 cm', habitat: ['濕地', '草原'], diet: '魚、昆蟲',
    features: '栗紅色頭、寶藍背、白胸',
    funFact: '白胸翡翠羽色鮮豔，是濕地的藍寶石！',
    description: '常於水邊或草地捕食，色彩亮麗。',
    region: '濕地、鄉郊', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.wetland, HOTSPOTS.longvalley, HOTSPOTS.namsangwai, HOTSPOTS.taipo_park],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#1E40AF', emoji: '🐦', call: '嘰—嘰—',
    tags: ['留鳥', '水鳥'],
    aiRecognizable: true, aiConfidence: 0.92, merlinCode: 'wtkin1', ebirdCode: 'wtkin1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-048', lastUpdated: Date.now(), pack: 5, source: 'internal',
  },
  {
    id: 49, name: '褐翅鴉鵑', nameEn: 'Greater Coucal', nameYue: '毛雞', scientificName: 'Centropus sinensis',
    family: '杜鵑科', familyEn: 'Cuculidae', order: '鵑形目',
    size: '50 cm', habitat: ['草原', '灌木'], diet: '雜食',
    features: '黑身褐翼、紅眼',
    funFact: '褐翅鴉鵑叫聲低沉有趣，像在打鼓！',
    description: '大型鵑類，常於草叢中活動。',
    region: '新界鄉郊', season: '四季',
    hotspots: [HOTSPOTS.maipo, HOTSPOTS.namsangwai, HOTSPOTS.longvalley, HOTSPOTS.taipo_park, HOTSPOTS.yuen_long],
    globalRange: ['南亞', '東南亞'],
    baseColor: '#1A1A1A', emoji: '🦅', call: '叩—叩—叩',
    tags: ['留鳥'],
    aiRecognizable: true, aiConfidence: 0.82, merlinCode: 'grecou1', ebirdCode: 'grecou1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-049', lastUpdated: Date.now(), pack: 5, source: 'internal',
  },
  {
    id: 50, name: '鳳頭鸚鵡', nameEn: 'Yellow-crested Cockatoo', nameYue: '葵花鸚鵡', scientificName: 'Cacatua sulphurea',
    family: '鳳頭鸚鵡科', familyEn: 'Cacatuidae', order: '鸚形目',
    size: '33 cm', habitat: ['都市'], diet: '種子、果實',
    features: '純白羽毛、黃色頭冠',
    funFact: '香港的鳳頭鸚鵡族群估計有 200 隻，源自二戰時籠中鳥逃逸！',
    description: '外來種但香港特色，可見於香港島花園。',
    region: '香港島', season: '四季',
    hotspots: [HOTSPOTS.hkpark, HOTSPOTS.botanical, HOTSPOTS.victoria_park, HOTSPOTS.peak, HOTSPOTS.central_pier],
    globalRange: ['印尼（原生）', '香港（歸化）'],
    baseColor: '#FCD34D', emoji: '🦜', call: '尖叫聲',
    tags: ['外來種', '明星鳥', '瀕危'],
    aiRecognizable: true, aiConfidence: 0.96, merlinCode: 'yecock1', ebirdCode: 'yecock1',
    photoUrl: null, illustrationUrl: null, audioUrl: null,
    notionId: 'nt-050', lastUpdated: Date.now(), pack: 5, source: 'internal',
  },
];

// === 合併後台覆蓋 ===
export function mergeSpecies(
  internal: BirdSpecies[],
  remoteOverrides: Record<number, Partial<BirdSpecies>>
): BirdSpecies[] {
  const merged = internal.map((s) => {
    const remote = remoteOverrides[s.id];
    if (remote) return { ...s, ...remote, source: 'remote' as const };
    return s;
  });
  Object.entries(remoteOverrides).forEach(([idStr, r]) => {
    const id = Number(idStr);
    if (!merged.find((m) => m.id === id) && r.name) {
      merged.push({ ...r, id } as BirdSpecies);
    }
  });
  return merged.sort((a, b) => a.id - b.id);
}

export function getSpecies(all: BirdSpecies[], id: number): BirdSpecies | undefined {
  return all.find((s) => s.id === id);
}

// === 辨識 ===
export interface RecognizeResult {
  success: boolean;
  species?: BirdSpecies;
  confidence?: number;
  reason?: string;
  alternatives?: { species: BirdSpecies; confidence: number }[];
}

export function simulateRecognize(allSpecies: BirdSpecies[]): RecognizeResult {
  const aiFailureRate = 0.25;
  const roll = Math.random();
  if (roll < aiFailureRate) {
    const reasons = ['角度不佳', '光線不足', '距離太遠', '背景干擾', '姿勢模糊'];
    return {
      success: false,
      reason: reasons[Math.floor(Math.random() * reasons.length)],
    };
  }
  const candidates = allSpecies.filter((s) => s.aiRecognizable);
  if (candidates.length === 0) return { success: false, reason: '資料庫尚無可辨識鳥種' };
  const picked = candidates[Math.floor(Math.random() * candidates.length)];
  const confidence = picked.aiConfidence || 0.8;
  const alternatives = candidates
    .filter((c) => c.id !== picked.id && c.family === picked.family)
    .slice(0, 2)
    .map((s) => ({ species: s, confidence: Math.random() * 0.3 + 0.1 }));
  return { success: true, species: picked, confidence, alternatives };
}

// === Notion 資料模組 ===
export interface NotionModule {
  key: string;
  name: string;
  icon: string;
  color: string;
  desc: string;
  count: number;
  fields: string[];
  adminLevel: 'parent' | 'super';
}

export const NOTION_MODULES: NotionModule[] = [
  {
    key: 'species', name: '鳥類物種', icon: 'albums', color: '#00E5FF',
    desc: '鳥類基本資料、特徵、辨識資訊',
    count: 50, fields: ['id', 'name', 'family', 'merlinCode', 'ebirdCode', 'aiRecognizable'],
    adminLevel: 'super',
  },
  {
    key: 'cards', name: '卡牌樣式', icon: 'diamond', color: '#B388FF',
    desc: '卡牌外觀、顏色、稀有度設計',
    count: 7, fields: ['rarity', 'gradient', 'glow', 'frame', 'holographic'],
    adminLevel: 'super',
  },
  {
    key: 'photos', name: '鳥類照片', icon: 'image', color: '#00FF94',
    desc: '實體照片 URL（替代 emoji）',
    count: 0, fields: ['birdId', 'photoUrl', 'source', 'license'],
    adminLevel: 'super',
  },
  {
    key: 'audio', name: '鳥類叫聲', icon: 'volume-high', color: '#FFD740',
    desc: 'Macaulay Library 叫聲 MP3',
    count: 0, fields: ['birdId', 'audioUrl', 'duration', 'recordist'],
    adminLevel: 'super',
  },
  {
    key: 'review', name: '審核紀錄', icon: 'checkmark-done', color: '#FF8A4C',
    desc: '家長/老師審核紀錄與統計',
    count: 0, fields: ['photoId', 'reviewer', 'result', 'timestamp'],
    adminLevel: 'parent',
  },
  {
    key: 'events', name: '活動主題', icon: 'flag', color: '#FF4DA6',
    desc: '特定活動對應鳥類（如候鳥季、觀鳥日）',
    count: 5, fields: ['eventName', 'targetBirds', 'startDate', 'endDate', 'reward'],
    adminLevel: 'super',
  },
  {
    key: 'settings', name: '系統設定', icon: 'settings', color: '#5BB3FF',
    desc: '密碼管理、辨識閾值、語言設定',
    count: 8, fields: ['parentPassword', 'aiThreshold', 'language'],
    adminLevel: 'super',
  },
];
