// 多語言支援 (中/英/粵)
export type Language = 'zh' | 'en' | 'yue';

export const LANGUAGES: Record<Language, { label: string; flag: string }> = {
  zh: { label: '中文', flag: '🇹🇼' },
  en: { label: 'English', flag: '🇬🇧' },
  yue: { label: '粵語', flag: '🇭🇰' },
};

export const i18n = {
  zh: {
    app_title: 'BIRD-DEX',
    app_subtitle: '兒童賞鳥捕捉器',
    tab_dex: '圖鑑',
    tab_capture: '捕捉',
    tab_map: '地圖',
    tab_notion: '後台',
    tab_trainer: '訓練家',
    capture_btn: '開始捕捉',
    scanning: '掃描中...',
    new_species: '新物種！',
    rarity_up: '稀有度升級！',
    map_title: '尋鳥地圖',
    gps_on: 'GPS 開啟',
    gps_off: '開啟 GPS',
    hk_map: '香港地圖',
    world_map: '世界分布',
    notion_title: '資料管理',
    sync_now: '立即同步',
    admin_entry: '後台人員入口',
    settings_lang: '語言',
    settings_medals: '紀念章',
    settings_titles: '職稱',
  },
  en: {
    app_title: 'BIRD-DEX',
    app_subtitle: 'Kids Birding Catcher',
    tab_dex: 'Dex',
    tab_capture: 'Catch',
    tab_map: 'Map',
    tab_notion: 'Notion',
    tab_trainer: 'Trainer',
    capture_btn: 'Start Capture',
    scanning: 'Scanning...',
    new_species: 'NEW SPECIES!',
    rarity_up: 'RARITY UP!',
    map_title: 'Bird Map',
    gps_on: 'GPS ON',
    gps_off: 'Enable GPS',
    hk_map: 'Hong Kong',
    world_map: 'World',
    notion_title: 'Data Manager',
    sync_now: 'Sync Now',
    admin_entry: 'Admin Entry',
    settings_lang: 'Language',
    settings_medals: 'Medals',
    settings_titles: 'Titles',
  },
  yue: {
    app_title: 'BIRD-DEX',
    app_subtitle: '小朋友觀鳥捕捉器',
    tab_dex: '圖鑑',
    tab_capture: '影相',
    tab_map: '地圖',
    tab_notion: '後台',
    tab_trainer: '訓練員',
    capture_btn: '開始影',
    scanning: '識別中...',
    new_species: '新品種！',
    rarity_up: '升級咗！',
    map_title: '搵鳥地圖',
    gps_on: 'GPS 開咗',
    gps_off: '開 GPS',
    hk_map: '香港地圖',
    world_map: '全世界',
    notion_title: '資料管理',
    sync_now: '即刻更新',
    admin_entry: '後台入口',
    settings_lang: '語言',
    settings_medals: '紀念章',
    settings_titles: '職稱',
  },
};

export function t(lang: Language, key: keyof typeof i18n.zh): string {
  return i18n[lang][key] || key;
}
